version: "3.8"
services:
  api:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000 # host:container
    volumes:
      - .:/usr/src/app # host:container (WORKDIR)
    environment:
      PGUSER: development_user
      PGPASSWORD: testing
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: bugtracker_backend_database
      NODE_ENV: development
      SESSIONS_SECRET: testing
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: bugtracker_backend_database_user
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: bugtracker_backend_database
    ports:
      - "5432:5432" # host:container
    volumes:
      - ./bugtracker.sql:/docker-entrypoint-initdb.d/init.sql # start the db with this schema
  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch_container
    environment:
      - discovery.type=single-node
      - cluster.name=bugtracker_cluster
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana_container
    ports: 
      - 5601:5601