apiVersion: apps/v1
kind: Deployment
metadata:
  # Name of the deployment
  name: frontend
spec:
  selector:
    matchLabels:
      # the labels that should be used to select the pods that this deployment will manage
      # I used app: frontend but I also could've used service: foo
      app: frontend

  # what template should all the pods use
  template:
    metadata:
      labels:
        # what labels should be applied to the pods 
        app: frontend
    spec:
      # I got the user/group ID for this by running `make nerdctl-shell-frontend` and then by running `cat /etc/passwd`
      securityContext:
        runAsUser: 101
        runAsNonRoot: true
        fsGroup: 101
        runAsGroup: 101
      
      # what containers should each pod be running
      containers:
        - name: frontend/nginx
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true
          image: cstudent/frontend
          ports:
          - containerPort: 80
            protocol: TCP
          # readinessProbe:
          #   initialDelaySeconds: 10
          #   httpGet:
          #     path: "/_health"
          #     port: 80
          #     httpHeaders:
          #     - name: "Cookie"
          #       value: "shop_session-id=x-readiness-probe"
          # livenessProbe:
          #   initialDelaySeconds: 10
          #   httpGet:
          #     path: "/_health"
          #     port: 80
          #     httpHeaders:
          #     - name: "Cookie"
          #       value: "shop_session-id=x-liveness-probe"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      # the port that the service will be listening on for traffic
      port: 3000
      # the port that the pods will use to listen to traffic
      targetPort: 80